/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AddonsIndexRouteImport } from './routes/addons.index'
import { Route as AddonsAddonRouteImport } from './routes/addons.$addon'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'
import { Route as CreatorsIndexRouteImport } from './routes/creators.index'
import { Route as CreatorsCreatorRouteImport } from './routes/creators.$creator'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsRequestRouteImport } from './routes/requests.$request'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsIndexRoute = AddonsIndexRouteImport.update({
  id: '/addons/',
  path: '/addons/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsAddonRoute = AddonsAddonRouteImport.update({
  id: '/addons/$addon',
  path: '/addons/$addon',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsIndexRoute = CreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsCreatorRoute = CreatorsCreatorRouteImport.update({
  id: '/creators/$creator',
  path: '/creators/$creator',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestRoute = RequestsRequestRouteImport.update({
  id: '/requests/$request',
  path: '/requests/$request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/submit': typeof SubmitRoute
  '/addons/$addon': typeof AddonsAddonRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/creators/$creator': typeof CreatorsCreatorRoute
  '/requests/$request': typeof RequestsRequestRoute
  '/addons/': typeof AddonsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/creators/': typeof CreatorsIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/submit': typeof SubmitRoute
  '/addons/$addon': typeof AddonsAddonRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/creators/$creator': typeof CreatorsCreatorRoute
  '/requests/$request': typeof RequestsRequestRoute
  '/addons': typeof AddonsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/creators': typeof CreatorsIndexRoute
  '/requests': typeof RequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/submit': typeof SubmitRoute
  '/addons/$addon': typeof AddonsAddonRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/creators/$creator': typeof CreatorsCreatorRoute
  '/requests/$request': typeof RequestsRequestRoute
  '/addons/': typeof AddonsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/creators/': typeof CreatorsIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/submit'
    | '/addons/$addon'
    | '/categories/$category'
    | '/creators/$creator'
    | '/requests/$request'
    | '/addons/'
    | '/categories/'
    | '/creators/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/submit'
    | '/addons/$addon'
    | '/categories/$category'
    | '/creators/$creator'
    | '/requests/$request'
    | '/addons'
    | '/categories'
    | '/creators'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/submit'
    | '/addons/$addon'
    | '/categories/$category'
    | '/creators/$creator'
    | '/requests/$request'
    | '/addons/'
    | '/categories/'
    | '/creators/'
    | '/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SubmitRoute: typeof SubmitRoute
  AddonsAddonRoute: typeof AddonsAddonRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  CreatorsCreatorRoute: typeof CreatorsCreatorRoute
  RequestsRequestRoute: typeof RequestsRequestRoute
  AddonsIndexRoute: typeof AddonsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CreatorsIndexRoute: typeof CreatorsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons/': {
      id: '/addons/'
      path: '/addons'
      fullPath: '/addons/'
      preLoaderRoute: typeof AddonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons/$addon': {
      id: '/addons/$addon'
      path: '/addons/$addon'
      fullPath: '/addons/$addon'
      preLoaderRoute: typeof AddonsAddonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/': {
      id: '/creators/'
      path: '/creators'
      fullPath: '/creators/'
      preLoaderRoute: typeof CreatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$creator': {
      id: '/creators/$creator'
      path: '/creators/$creator'
      fullPath: '/creators/$creator'
      preLoaderRoute: typeof CreatorsCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$request': {
      id: '/requests/$request'
      path: '/requests/$request'
      fullPath: '/requests/$request'
      preLoaderRoute: typeof RequestsRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SubmitRoute: SubmitRoute,
  AddonsAddonRoute: AddonsAddonRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  CreatorsCreatorRoute: CreatorsCreatorRoute,
  RequestsRequestRoute: RequestsRequestRoute,
  AddonsIndexRoute: AddonsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CreatorsIndexRoute: CreatorsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
